spring:
  application:
    name: PARKAWAY-BACKEND
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parkaway
    username: root
    password: databaseadmin
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: parkawayapplication@gmail.com
    password: rijisxgnzuqvnivv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

app:
  jwt:
    secret: PARKAWAY-Application-styerihFgn46cdbgd?
  company:
    name : Parkway

server:
  port: 8080

distance:
  matrix:
    api:
      url: https://api.distancematrix.ai/maps/api/distancematrix/json?
      key: Js6u1jWAc81OcMiAELL4L96m6PHVZ
