spring:
  application:
    name: PARKAWAY-BACKEND
  datasource:
    url: jdbc:mysql://vrkdb.cubuapboxrw3.ap-south-1.rds.amazonaws.com:3306/parkaway
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: gyanaranjan.shilu@gmail.com
    password: oavjerdhgoomddlp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

app:
  jwt:
    secret: PARKAWAY-Application-styerihFgn46cdbgd?
  company:
    name : Parkway

server:
  port: 8081
